### ISSUE TITLE
UrlCleaner.normalizeUrl  method throw URISyntaxException

### ISSUE THREAD

**Issue by oyxiaogua** [shekhargulati/urlcleaner#1]
```
 I found that there are some problems with the normalizeurl method:
` String rtnStr = UrlCleaner.normalizeUrl("stackoverflow.com/questions/tagged/java");
   System.out.println(rtnStr);`

the code above throws the following exception:

`Caused by: java.net.URISyntaxException: Relative path in absolute URI: http://stackoverflow.com%5Cquestions%5Ctagged%5Cjava
  at java.net.URI.checkPath(URI.java:1823)
  at java.net.URI.<init>(URI.java:672)
  at com.shekhargulati.urlcleaner.UrlCleaner.normalizeUrl(UrlCleaner.java:59)
  ... 25 more`
```

**Comment by shekhargulati** [comment]
@oyxiaogua I wrote a test case for your usecase and it passed. You can look at the test case here https://github.com/shekhargulati/urlcleaner/blob/master/src/test/java/com/shekhargulati/urlcleaner/UrlCleanerSpec.java#L265. Can you create a test case for your scenario and raise a PR?

**Comment by oyxiaogua** [comment]
```
`String path = uri.getPath();
if (path != null) {
    path = Paths.get(path).normalize().toString();
}`
```

   at the beginning path is "/",after execute the code,the path become "\",then 
   `newUri = new URI(scheme, uri.getUserInfo(), host, port, path, sortQueryString(uri.getQuery()), fragment).normalize().toString();`
  throw an exception.
  i'm using window system.please ignore it if i'm wrong,thanks.
